#!/usr/bin/env ruby

require 'yaml'
require 'fileutils'
require 'mruby/bindings'

$output_dirname = "./mruby-bindings.out/blueprint"
FileUtils.mkdir_p $output_dirname

$ctypes_file = File.open("#{$output_dirname}/ctypes.yaml", 'w')

CSV.foreach('./mruby-bindings.out/blueprint/functions.csv', headers: true) do |row|
  MRuby::Bindings::CTypes.read_function_blueprint(row)
end

MRuby::Bindings::CTypes.each.sort_by { |k, v| k }.each do |k, ctype|
  $ctypes_file.puts YAML.dump(ctype)
end
