#!/usr/bin/env ruby

require 'json'
require 'csv'
require 'fileutils'
require 'mruby/bindings'

$parmdecl_filename = './mruby-bindings.out/ingested-declarations/parm-decl.json'
$output_dirname = './mruby-bindings.out/discovery'
$output_filename = "#{$output_dirname}/parms.csv"

FileUtils.rm_rf $output_filename if File.exists?($output_filename)
FileUtils.mkdir_p $output_dirname unless Dir.exists?($output_dirname)

$columns = %w(function name type)

CSV.open($output_filename, 'w') do |output_file|
  output_file.puts $columns
  File.open($parmdecl_filename, 'r') do |parmdecl_file|
    while line = parmdecl_file.gets
      parm = JSON.parse(line)
      output_file << [
        parm['function'][/@([^@]+)$/, 1],
        parm['name'],
        parm['type']['type_name']
      ]
    end
  end
end
