#!/usr/bin/env ruby

require "yaml"
require "mruby/bindings"

YAML.load_stream(File.open("#{MRuby::Bindings::Paths::RENDER_DIR}/#{ARGV[0]}.yaml"))
    .each do |t|
        puts t.body
        puts
    end
