#!/usr/bin/env ruby

require 'json'
require 'fileutils'

$declaration_files = ['declarations.json']
$output_dirname = 'mruby-bindings.out/ingested-declarations'

FileUtils.rm_rf $output_dirname if Dir.exists?($output_dirname)
FileUtils.mkdir_p $output_dirname

module OutFiles
  def self.[](filename)
    @files ||= {}
    @files[filename] ||= File.open($output_dirname + '/' + filename + ".json", 'a')
  end

  def self.close
    @files ||= {}
    @files.each do |k, f|
      f.close
    end
  end
end

$declaration_files.each do |declaration_filename|
  open(declaration_filename, 'r') do |declaration_file|
    while line = declaration_file.gets
      decl = JSON.parse(line)
      outfile = OutFiles[decl['kind']]
      outfile.puts(line)
    end
  end
end

OutFiles.close
