#!/usr/bin/env ruby

require 'fileutils'
require 'mruby/bindings'

main_c_filename = "mruby_#{MRuby::Bindings::Hooks.module_name}.c"
main_c_source_path = "#{MRuby::Bindings::Paths::RESULT_DIR}/src/#{main_c_filename}"
main_c_target_path = "./src/#{main_c_filename}"

mrbgem_rake_source_path = "#{MRuby::Bindings::Paths::RESULT_DIR}/mrbgem.rake"
mrbgem_rake_target_path = "./mrbgem.rake"

FileUtils.mkdir_p "./include/generated" unless Dir.exists?("./include/generated")
FileUtils.mkdir_p "./src/generated" unless Dir.exists?("./src/generated")
FileUtils.cp_r Dir["#{MRuby::Bindings::Paths::RESULT_DIR}/include/generated/*"], './include/generated'
FileUtils.cp_r Dir["#{MRuby::Bindings::Paths::RESULT_DIR}/src/generated/*"], './src/generated'
FileUtils.cp_r main_c_source_path, main_c_target_path unless File.exists?(main_c_target_path)
FileUtils.cp_r mrbgem_rake_source_path, mrbgem_rake_target_path unless File.exists?(mrbgem_rake_target_path)
